baseurl: "/vim-pack" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


permalink: pretty

nav:
  - Getting Started:
    - Introduction: ''
    - Install: install
    - Plugins: plugins
  - Usages:
    - usages
  - Licence:
      - WTFPL: license



owner_name: tanvir hasan
owner_url: https://www.facebook.com/anick.silentkiller


# Build settings
markdown: kramdown
remote_theme: marella/jekyll-theme-documentation
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
